version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: aiueducation-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads:/var/uploads
    depends_on:
      - app

  app:
    build: .
    container_name: aiueducation-app
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DATABASE_URL=jdbc:postgresql://db:5432/${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    expose:
      - "8080"
    volumes:
      - uploads:/var/uploads
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: aiueducation-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  postgres_data:
  uploads: 