version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: aiueducation-app-simple
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=jdbc:postgresql://db:5432/aiueducation_db
      - DATABASE_USERNAME=aiueducation_user
      - DATABASE_PASSWORD=aiueducation_pass
    ports:
      - "8080:8080"
    volumes:
      - uploads:/var/uploads
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: aiueducation-db-simple
    restart: unless-stopped
    environment:
      - POSTGRES_DB=aiueducation_db
      - POSTGRES_USER=aiueducation_user
      - POSTGRES_PASSWORD=aiueducation_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_simple:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aiueducation_user -d aiueducation_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer - простая веб-админка для БД (как Django Admin)
  adminer:
    image: adminer:latest
    container_name: aiueducation-adminer-simple
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db

volumes:
  postgres_data_simple:
  uploads: 